site_name: Bastian Politycki
docs_dir: src
theme:
  name: material
  favicon: images/favicon.ico
  features:
    - navigation.top
  palette:
    primary: purple
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bpolitycki
    - icon: material/email
      link: mailto:bastian.politycki@unisg.ch
plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: de
copyright: "&copy; Bastian Politycki"
