name: Publish on GitHub Pages

on:
  create:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.11
        run: uv python install 3.11
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Publish with mkdocs
        run: uv run mkdocs gh-deploy --force
